### ISSUE TITLE
ticketテーブル作成エラー

### ISSUE THREAD

**Issue by pazworld** [bearsunday/Tutorial2#7]
# 現象

ticket テーブルを作成するために `composer setup` を実行するとプライマリキーのNULL制約についてのエラーが発生します。

```
/workspaces/MyVendor.Ticket$ composer setup
> php bin/setup.php
Phinx by CakePHP - https://phinx.org.

using config file var/phinx/phinx.php
using config parser php
using migration paths 
 - /workspaces/MyVendor.Ticket/var/phinx/migrations
using environment development
using database ticket
ordering by creation time

 == 20221017052941 Ticket: migrating 
PDOException: SQLSTATE[42000]: Syntax error or access violation: 1171 All parts of a PRIMARY KEY must be NOT NULL; if you need NULL in a key, use UNIQUE instead in /workspaces/MyVendor.Ticket/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php:192
Stack trace:
#0 /workspaces/MyVendor.Ticket/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php(192): PDO->exec('CREATE TABLE `t...')
#1 /workspaces/MyVendor.Ticket/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/MysqlAdapter.php(357): Phinx\Db\Adapter\PdoAdapter->execute('CREATE TABLE `t...')
#2 /workspaces/MyVendor.Ticket/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/AdapterWrapper.php(349): Phinx\Db\Adapter\MysqlAdapter->createTable(Object(Phinx\Db\Table\Table), Array, Array)
#3 /workspaces/MyVendor.Ticket/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/TimedOutputAdapter.php(113): Phinx\Db\Adapter\AdapterWrapper->createTable(Object(Phinx\Db\Table\Table), Array, Array)
#4 /workspaces/MyVendor.Ticket/vendor/robmorgan/phinx/src/Phinx/Db/Plan/Plan.php(146): Phinx\Db\Adapter\TimedOutputAdapter->createTable(Object(Phinx\Db\Table\Table), Array, Array)
#5 /workspaces/MyVendor.Ticket/vendor/robmorgan/phinx/src/Phinx/Db/Table.php(716): Phinx\Db\Plan\Plan->execute(Object(Phinx\Db\Adapter\TimedOutputAdapter))
#6 /workspaces/MyVendor.Ticket/vendor/robmorgan/phinx/src/Phinx/Db/Table.php(612): Phinx\Db\Table->executeActions(false)
#7 /workspaces/MyVendor.Ticket/var/phinx/migrations/20221017052941_ticket.php(25): Phinx\Db\Table->create()
#8 /workspaces/MyVendor.Ticket/vendor/robmorgan/phinx/src/Phinx/Migration/Manager/Environment.php(108): Ticket->change()
#9 /workspaces/MyVendor.Ticket/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(388): Phinx\Migration\Manager\Environment->executeMigration(Object(Ticket), 'up', false)
#10 /workspaces/MyVendor.Ticket/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(359): Phinx\Migration\Manager->executeMigration('development', Object(Ticket), 'up', false)
#11 /workspaces/MyVendor.Ticket/vendor/robmorgan/phinx/src/Phinx/Console/Command/Migrate.php(122): Phinx\Migration\Manager->migrate('development', 20221017052941, false)
#12 /workspaces/MyVendor.Ticket/vendor/symfony/console/Command/Command.php(291): Phinx\Console\Command\Migrate->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /workspaces/MyVendor.Ticket/vendor/symfony/console/Application.php(1002): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /workspaces/MyVendor.Ticket/vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application->doRunCommand(Object(Phinx\Console\Command\Migrate), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /workspaces/MyVendor.Ticket/vendor/robmorgan/phinx/src/Phinx/Console/PhinxApplication.php(70): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /workspaces/MyVendor.Ticket/vendor/symfony/console/Application.php(171): Phinx\Console\PhinxApplication->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /workspaces/MyVendor.Ticket/vendor/robmorgan/phinx/bin/phinx(28): Symfony\Component\Console\Application->run()
#18 /workspaces/MyVendor.Ticket/vendor/bin/phinx(120): include('/workspaces/MyV...')
#19 {main}
Phinx by CakePHP - https://phinx.org.
```

# 環境

- PHP 8.0.12 (Docker container PHP:8-alpine)
- MySQL 8.0.31 (Docker container mysql:8-debian)

# 実行SQLの調査

どんなSQL文が実行されているか調べるため `vendor/robmorgan/phix/src/Db/Adapter/PdoAdapter.php` の192行目にechoを入れました。

```diff
    public function execute(string $sql, array $params = []): int
    {
        $sql = rtrim($sql, "; \t\n\r\0\x0B") . ';';
        $this->verboseLog($sql);

        if ($this->isDryRunEnabled()) {
            return 0;
        }

        if (empty($params)) {
+           echo PHP_EOL . 'SQL => ' . $sql . PHP_EOL;
            return $this->getConnection()->exec($sql);
        }

        $stmt = $this->getConnection()->prepare($sql);
        $result = $stmt->execute($params);

        return $result ? $stmt->rowCount() : $result;
    }
```

`composer setup` を実行すると次のように表示されました。

```sql
SQL => CREATE TABLE `ticket` (`id` CHAR(36) NULL, `title` VARCHAR(255) NULL, `date_created` DATETIME NULL, PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
```

`id` 列が NULL 許可になっています。

これはMySQL 5.7.3で修正された「プライマリキーはNOT NULLでなければならない」という仕様に違反しています。

https://dev.mysql.com/doc/relnotes/mysql/5.7/en/news-5-7-3.html#mysqld-5-7-3-bug

> Columns in a PRIMARY KEY must be NOT NULL, but if declared explicitly as NULL produced no error. Now an error occurs. For example, a statement such as [CREATE TABLE t (i INT NULL PRIMARY KEY)](https://dev.mysql.com/doc/refman/5.7/en/create-table.html) is rejected.

(とはいえ MySQL 5.7.3 は2013年なので、今ごろ急に影響が出るとは考えにくいです)

# とりあえず動作させる方法

マイグレーションファイル `var/phinx/migrations/XXXX_ticket.php` で `id` 列に `'null' => false` オプションを付けることでエラーが出なくなりテーブルが作成されました。

```diff
    public function change()
    {
        $table = $this->table('ticket', ['id' => false, 'primary_key' => ['id']]);
-       $table->addColumn('id', 'uuid')
+       $table->addColumn('id', 'uuid', ['null' => false])
            ->addColumn('title', 'string')
            ->addColumn('date_created', 'datetime')
            ->create();
    }
```

とはいえ、これが正解かわかりません。

**Comment by koriym** [comment]
@pazworld 遅い返信すいません！

Phinxがupdateされたからか今はエラーが出ないようです。CIを作成しました。

https://github.com/bearsunday/tutorial2/actions/runs/7592131035/job/20681112186#step:6:262

**Comment by koriym** [comment]
@pazworld 他の環境で確認しました><

**Comment by koriym** [comment]
@pazworld 修正しました。ありがとうございました！

**Comment by pazworld** [comment]
👍
